// Makes the build an installable, offline-capable web app — what an iPhone's
// "Add to Home Screen" and Android's "Install app" use. At build time it:
//   • draws the home-screen icons (tools/icon.mjs) and writes the web app manifest,
//   • adds the iOS/Android tags to index.html,
//   • writes sw.js, a service worker that caches every file of this build, so
//     the game (TypeScript compiler included) works with no connection.
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { drawIcon } from './icon.mjs';

export const APP = {
  name: 'Reactor Quest',
  shortName: 'Reactor',
  description: 'Learn TypeScript and React from zero to professional by restoring a dark space station.',
  background: '#070b16',
};

export const ICONS = [
  { file: 'icons/icon-192.png', size: 192, tile: 'square' },
  { file: 'icons/icon-512.png', size: 512, tile: 'square', ss: 2 },
  // Android crops "maskable" icons to a circle, squircle…: keep the art inside the safe zone.
  { file: 'icons/icon-maskable-512.png', size: 512, tile: 'square', scale: 0.78, ss: 2, purpose: 'maskable' },
  // iOS rounds the corners itself, so it wants a full-bleed square.
  { file: 'icons/apple-touch-icon.png', size: 180, tile: 'square' },
];

const manifest = () => ({
  name: APP.name,
  short_name: APP.shortName,
  description: APP.description,
  id: './',
  start_url: './',
  scope: './',
  display: 'standalone',
  orientation: 'any',
  background_color: APP.background,
  theme_color: APP.background,
  categories: ['education', 'games'],
  icons: ICONS.filter((i) => i.file.includes('icon-')).map((i) => ({ src: i.file, sizes: `${i.size}x${i.size}`, type: 'image/png', ...(i.purpose ? { purpose: i.purpose } : {}) })),
});

/** The service worker: precache the build; hashed assets cache-first, the page network-first. */
const serviceWorker = (version, files) => `// Generated by tools/pwa.mjs — the offline cache for this build.
const CACHE = 'reactor-quest-${version}';
const FILES = ${JSON.stringify(files)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES.map((f) => './' + f))));
  self.skipWaiting();
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('reactor-quest-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin || url.pathname.includes('/__')) return;
  if (req.mode === 'navigate') {
    // The page itself: fresh when online (so updates arrive), cached when not.
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          if (res.ok) caches.open(CACHE).then((c) => c.put('./index.html', copy));
          return res;
        })
        .catch(() => caches.match('./index.html')),
    );
    return;
  }
  e.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;

/** @returns {import('vite').Plugin} */
export function pwa() {
  return {
    name: 'reactor-pwa',
    apply: 'build',
    enforce: 'post',
    transformIndexHtml: () => [
      { tag: 'link', attrs: { rel: 'manifest', href: './manifest.webmanifest' }, injectTo: 'head' },
      { tag: 'link', attrs: { rel: 'apple-touch-icon', href: './icons/apple-touch-icon.png' }, injectTo: 'head' },
    ],
    generateBundle() {
      for (const icon of ICONS) this.emitFile({ type: 'asset', fileName: icon.file, source: drawIcon(icon.size, { tile: icon.tile, scale: icon.scale, ss: icon.ss }) });
      this.emitFile({ type: 'asset', fileName: 'manifest.webmanifest', source: JSON.stringify(manifest(), null, 2) });
    },
    writeBundle(options, bundle) {
      const files = Object.keys(bundle).sort();
      const version = createHash('sha256').update(files.join('\n')).update(String(bundle['index.html']?.source ?? '')).digest('hex').slice(0, 12);
      writeFileSync(join(options.dir, 'sw.js'), serviceWorker(version, files));
    },
  };
}
