import type { ArcadeCard } from '../game/types';

// "Compiles?" — every card's verdict is verified against the real compiler
// (strict mode, same settings as the levels) by tests/arcade.test.ts.
export const ARCADE_CARDS: ArcadeCard[] = [
  { code: `let fuel: number = "80";`, ok: false, why: 'A string literal is not a number. Annotations are promises the compiler holds you to.' },
  { code: `const names: string[] = ["Ada", "Bo"];\nnames.push("Cy");`, ok: true, why: '`const` stops reassigning the variable, not changing the array it points to.' },
  { code: `function greet(name) {\n  return "Hi " + name;\n}`, ok: false, why: 'Under strict mode, an unannotated parameter is an implicit `any` — an error.' },
  { code: `let id: string | number = 7;\nid = "seven";`, ok: true, why: 'Both values fit the union `string | number`.' },
  { code: `function len(s: string | null) {\n  return s.length;\n}`, ok: false, why: '`s` is possibly `null`. Narrow it first.' },
  { code: `function len(s: string | null) {\n  return s?.length ?? 0;\n}`, ok: true, why: '`?.` short-circuits on null and `??` supplies the fallback.' },
  { code: `const pt: { x: number; y: number } = { x: 1 };`, ok: false, why: 'Property `y` is missing.' },
  { code: `interface Ship { name: string }\nconst s: Ship = { name: "Kite", crew: 3 };`, ok: false, why: 'Object literals get an excess property check: `crew` isn\'t in `Ship`.' },
  { code: `interface Ship { name: string }\nconst data = { name: "Kite", crew: 3 };\nconst s: Ship = data;`, ok: true, why: 'Gotcha! Excess property checks only apply to fresh object literals. `data` has a `name: string`, so it fits.' },
  { code: `type Dir = "up" | "down";\nconst d: Dir = "left";`, ok: false, why: '"left" is not one of the literal members of `Dir`.' },
  { code: `const pair: [string, number] = ["a", 1, 2];`, ok: false, why: 'A tuple has a fixed length. Three elements don\'t fit `[string, number]`.' },
  { code: `const nums = [1, 2, 3];\nconst doubled: number[] = nums.map((n) => n * 2);`, ok: true, why: '`n` is inferred as `number`, so the result is `number[]`.' },
  { code: `const nums = [1, 2, 3];\nconst hit: number = nums.find((n) => n > 1);`, ok: false, why: '`find` returns `number | undefined` — it might not find anything.' },
  { code: `function first<T>(xs: T[]): T | undefined {\n  return xs[0];\n}\nconst s: string | undefined = first([1, 2]);`, ok: false, why: 'T is inferred as `number`, so the result is `number | undefined`, not string.' },
  { code: `const ro: readonly number[] = [1, 2];\nro.push(3);`, ok: false, why: 'Readonly arrays have no `push`.' },
  { code: `let v: unknown = "hi";\nv.toUpperCase();`, ok: false, why: '`unknown` must be narrowed before you can use it.' },
  { code: `let v: unknown = "hi";\nif (typeof v === "string") v.toUpperCase();`, ok: true, why: 'The `typeof` check narrows `unknown` to `string`.' },
  { code: `let a: any = 4;\na.fly.to.the.moon();`, ok: true, why: '`any` turns checking off. It compiles — and crashes at runtime. That\'s why `any` is dangerous.' },
  { code: `function sign(n: number): string {\n  if (n > 0) return "pos";\n}`, ok: false, why: 'Not every path returns a string: for n ≤ 0 it returns `undefined`.' },
  { code: `const o = { level: 1 } as const;\no.level = 2;`, ok: false, why: '`as const` makes every property readonly.' },
  { code: `type User = { name: string; age?: number };\nconst u: User = { name: "Ada" };\nconst next = u.age + 1;`, ok: false, why: '`u.age` is possibly `undefined`.' },
  { code: `const el = document.querySelector("input");\nel.value = "x";`, ok: false, why: '`querySelector` returns `HTMLInputElement | null`. It might not exist.' },
  { code: `const el = document.querySelector("input");\nif (el) el.value = "x";`, ok: true, why: 'With a tag name, TypeScript knows it\'s an `HTMLInputElement`, and the `if` removes `null`.' },
  { code: `const el = document.querySelector(".field");\nif (el) el.value = "x";`, ok: false, why: 'A class selector gives a plain `Element`, which has no `value`. You\'d need `querySelector<HTMLInputElement>(…)`.' },
  { code: `import { useState } from "react";\nfunction Fuel() {\n  const [n, setN] = useState(0);\n  setN("full");\n  return null;\n}`, ok: false, why: '`useState(0)` holds a number; "full" is a string.' },
  { code: `function Badge({ name }: { name: string }) {\n  return <b>{name}</b>;\n}\nconst el = <Badge />;`, ok: false, why: 'The required prop `name` is missing.' },
  { code: `function Badge({ name }: { name: string }) {\n  return <b>{name}</b>;\n}\nconst el = <Badge name="Ada" />;`, ok: true, why: 'All required props are there, with the right types.' },
  { code: `const el = <div class="panel" />;`, ok: false, why: 'In JSX it\'s `className`. The compiler even suggests it.' },
  { code: `const el = (\n  <input onChange={(e) => console.log(e.target.value)} />\n);`, ok: true, why: 'The handler\'s event type is inferred from `onChange` on an `<input>`, so `e.target.value` is a string.' },
  { code: `import { useState } from "react";\nfunction List() {\n  const [items, setItems] = useState([]);\n  setItems(["fuel"]);\n  return null;\n}`, ok: false, why: '`useState([])` infers `never[]` — an array that can hold nothing. Write `useState<string[]>([])`.' },
  { code: `import { useRef } from "react";\nfunction Field() {\n  const r = useRef<HTMLInputElement>(null);\n  r.current.focus();\n  return <input ref={r} />;\n}`, ok: false, why: '`r.current` is `null` until React attaches it. Use `r.current?.focus()`.' },
  { code: `type Shape =\n  | { kind: "sq"; size: number }\n  | { kind: "circ"; r: number };\nconst area = (s: Shape) =>\n  s.kind === "sq" ? s.size ** 2 : Math.PI * s.r ** 2;`, ok: true, why: 'Checking the `kind` tag narrows each branch to one member.' },
  { code: `type Shape =\n  | { kind: "sq"; size: number }\n  | { kind: "circ"; r: number };\nconst size = (s: Shape) => s.size;`, ok: false, why: 'Without narrowing, `size` only exists on one member of the union.' },
  { code: `function sum(...xs: number[]) {\n  return xs.reduce((a, b) => a + b, 0);\n}\nsum(1, 2, "3");`, ok: false, why: '"3" is a string; every rest argument must be a number.' },
  { code: `const ages = new Map<string, number>();\nages.set("Ada", 31);\nconst a: number = ages.get("Ada");`, ok: false, why: '`Map.get` returns `number | undefined` — the key might be missing.' },
  { code: `function pick<T, K extends keyof T>(o: T, k: K) {\n  return o[k];\n}\npick({ a: 1 }, "b");`, ok: false, why: '"b" is not a key of `{ a: number }`.' },
  { code: `let maybe: string | undefined;\nconst s: string = maybe!;`, ok: true, why: 'The `!` non-null assertion silences the compiler. It\'s a promise, not a check — use it sparingly.' },
  { code: `const n = parseInt("42");\nconst s: string = n;`, ok: false, why: '`parseInt` returns a number.' },
  { code: `enum Mode { Idle, Burn }\nconst m: Mode = Mode.Burn;`, ok: true, why: 'Enum members are values of their enum type.' },
  { code: `import type { ReactNode } from "react";\nfunction Panel({ children }: { children: ReactNode }) {\n  return <section>{children}</section>;\n}\nconst p = <Panel>{42}{"text"}{null}</Panel>;`, ok: true, why: '`ReactNode` accepts numbers, strings, null, elements and arrays of them.' },
];
