package dev.foundry.core.docs;

import dev.foundry.core.expect.ExpectationRegistry;
import dev.foundry.core.expect.ExpectationRule;
import dev.foundry.core.plan.PipelinePlan;
import dev.foundry.core.plan.SinkPlan;
import dev.foundry.core.plan.StepPlan;
import dev.foundry.core.schema.PlanField;
import dev.foundry.core.transform.Transform;
import dev.foundry.core.transform.TransformRegistry;
import dev.foundry.metadata.MetadataRepository;
import dev.foundry.metadata.model.DatasetSpec;
import dev.foundry.metadata.model.ExpectationSpec;
import dev.foundry.metadata.model.FieldSpec;
import dev.foundry.metadata.model.ParamSpec;
import dev.foundry.metadata.model.SchemaSpec;

import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Generates a data catalogue from the metadata.
 *
 * <p>The catalogue is not maintained; it is derived. Schemas, datasets, pipeline
 * graphs and column lineage all come from the same documents the engine runs
 * from, so the page cannot describe a pipeline that no longer exists or miss a
 * column that was added last week. That is the quiet dividend of writing
 * metadata as code: the documentation stops being a promise somebody has to keep
 * and becomes a build output.
 */
public final class CatalogGenerator {

    private final MetadataRepository repository;
    private final List<PipelinePlan> plans;
    private final TransformRegistry transforms;
    private final ExpectationRegistry rules;

    public CatalogGenerator(MetadataRepository repository,
                            List<PipelinePlan> plans,
                            TransformRegistry transforms,
                            ExpectationRegistry rules) {
        this.repository = repository;
        this.plans = List.copyOf(plans);
        this.transforms = transforms;
        this.rules = rules;
    }

    public String generate() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Data catalogue").append(nl()).append(nl())
          .append("Generated by `foundry docs` from the metadata in `")
          .append(repository.root()).append("`. Do not edit by hand.").append(nl()).append(nl())
          .append("Metadata fingerprint: `").append(repository.fingerprint()).append('`')
          .append(nl()).append(nl());

        contents(sb);
        pipelines(sb);
        datasets(sb);
        schemas(sb);
        reference(sb);
        return sb.toString();
    }

    private void contents(StringBuilder sb) {
        sb.append("## Contents").append(nl()).append(nl());
        sb.append("- [Pipelines](#pipelines)").append(nl());
        for (PipelinePlan plan : plans) {
            sb.append("  - [").append(plan.name()).append("](#pipeline-").append(anchor(plan.name()))
              .append(')').append(nl());
        }
        sb.append("- [Datasets](#datasets)").append(nl());
        sb.append("- [Schemas](#schemas)").append(nl());
        sb.append("- [Transform reference](#transform-reference)").append(nl());
        sb.append("- [Quality rule reference](#quality-rule-reference)").append(nl()).append(nl());
    }

    // -------------------------------------------------------------- pipelines

    private void pipelines(StringBuilder sb) {
        sb.append("## Pipelines").append(nl()).append(nl());
        for (PipelinePlan plan : plans) {
            sb.append("### Pipeline: ").append(plan.name()).append(nl()).append(nl());
            if (plan.spec().description() != null) {
                sb.append(plan.spec().description().trim()).append(nl()).append(nl());
            }
            sb.append("Defined in `").append(plan.spec().where().file()).append('`')
              .append(nl()).append(nl());

            sb.append("```mermaid").append(nl()).append(plan.mermaid()).append("```")
              .append(nl()).append(nl());

            parameters(sb, plan.spec().params());
            steps(sb, plan);
            expectations(sb, plan);
            lineage(sb, plan);
        }
    }

    private void parameters(StringBuilder sb, List<ParamSpec> params) {
        if (params.isEmpty()) {
            return;
        }
        sb.append("#### Parameters").append(nl()).append(nl());
        sb.append("| Name | Type | Required | Default | Description |").append(nl());
        sb.append("| --- | --- | --- | --- | --- |").append(nl());
        for (ParamSpec param : params) {
            sb.append("| `").append(param.name()).append("` | `")
              .append(param.type().name().toLowerCase(Locale.ROOT)).append("` | ")
              .append(param.required() ? "yes" : "no").append(" | ")
              .append(param.defaultValue() == null ? "-" : "`" + param.defaultValue() + "`").append(" | ")
              .append(text(param.description())).append(" |").append(nl());
        }
        sb.append(nl());
    }

    private void steps(StringBuilder sb, PipelinePlan plan) {
        sb.append("#### Steps").append(nl()).append(nl());
        sb.append("| Step | Type | Reads | Produces | Detail |").append(nl());
        sb.append("| --- | --- | --- | --- | --- |").append(nl());
        for (StepPlan step : plan.steps()) {
            sb.append("| `").append(step.id()).append("` | `").append(step.type()).append("` | ")
              .append(step.inputs().isEmpty() ? "-" : "`" + String.join("`, `", step.inputs()) + "`")
              .append(" | ").append(step.output().size())
              .append(step.output().size() == 1 ? " column" : " columns").append(" | ")
              .append(step.transform().describeStep(step.spec()).map(detail -> "`" + detail + "`")
                      .orElse("-"))
              .append(" |").append(nl());
        }
        sb.append(nl());

        sb.append("<details><summary>Column detail</summary>").append(nl()).append(nl());
        for (StepPlan step : plan.steps()) {
            sb.append("**`").append(step.id()).append("`**");
            if (step.description() != null) {
                sb.append(" - ").append(text(step.description()));
            }
            sb.append(nl()).append(nl());
            sb.append("| Column | Planned type | Derived from |").append(nl());
            sb.append("| --- | --- | --- |").append(nl());
            for (PlanField field : step.output().fields()) {
                sb.append("| `").append(field.name()).append("` | `").append(field.typeName())
                  .append("` | ").append(field.origin() == null ? "-" : "`" + field.origin() + "`")
                  .append(" |").append(nl());
            }
            sb.append(nl());
        }
        sb.append("</details>").append(nl()).append(nl());
    }

    private void expectations(StringBuilder sb, PipelinePlan plan) {
        if (plan.expectations().isEmpty()) {
            return;
        }
        sb.append("#### Quality rules").append(nl()).append(nl());
        sb.append("| Expectation | Applied to | Rule | If broken |").append(nl());
        sb.append("| --- | --- | --- | --- |").append(nl());
        for (ExpectationSpec expectation : plan.expectations()) {
            sb.append("| `").append(expectation.name()).append("` | `").append(expectation.on())
              .append("` | `").append(expectation.rule()).append("` | ")
              .append(expectation.action().name().toLowerCase(Locale.ROOT)).append(" |").append(nl());
        }
        sb.append(nl());
    }

    private void lineage(StringBuilder sb, PipelinePlan plan) {
        if (plan.sinks().isEmpty()) {
            return;
        }
        sb.append("#### Column lineage").append(nl()).append(nl());
        sb.append("Every written column, traced back through the graph to the sources it reads.")
          .append(nl()).append(nl());
        for (SinkPlan sink : plan.sinks()) {
            sb.append("**`").append(sink.dataset().name()).append("`**").append(nl()).append(nl());
            sb.append("| Column | Comes from |").append(nl());
            sb.append("| --- | --- |").append(nl());
            Map<String, Set<String>> lineage = plan.lineage().sourcesOf(sink.from());
            lineage.forEach((column, origins) -> sb.append("| `").append(column).append("` | ")
                    .append(origins.isEmpty() ? "_a constant_"
                            : "`" + String.join("`, `", new java.util.TreeSet<>(origins)) + "`")
                    .append(" |").append(nl()));
            sb.append(nl());
        }
    }

    // --------------------------------------------------------------- datasets

    private void datasets(StringBuilder sb) {
        sb.append("## Datasets").append(nl()).append(nl());
        sb.append("| Dataset | Schema | Format | Location | Enforcement |").append(nl());
        sb.append("| --- | --- | --- | --- | --- |").append(nl());
        for (DatasetSpec dataset : repository.datasets()) {
            sb.append("| `").append(dataset.name()).append("` | [`").append(dataset.schema())
              .append("`](#schema-").append(anchor(dataset.schema())).append(") | `")
              .append(dataset.format()).append("` | `").append(dataset.location()).append("` | ")
              .append(dataset.enforcement().name().toLowerCase(Locale.ROOT)).append(" |").append(nl());
        }
        sb.append(nl());
        for (DatasetSpec dataset : repository.datasets()) {
            if (dataset.description() != null) {
                sb.append("**`").append(dataset.name()).append("`** - ")
                  .append(text(dataset.description())).append(nl()).append(nl());
            }
        }
    }

    // ---------------------------------------------------------------- schemas

    private void schemas(StringBuilder sb) {
        sb.append("## Schemas").append(nl()).append(nl());
        for (SchemaSpec schema : repository.schemas()) {
            sb.append("### Schema: ").append(schema.name())
              .append(" (v").append(schema.version()).append(')').append(nl()).append(nl());
            if (schema.description() != null) {
                sb.append(text(schema.description())).append(nl()).append(nl());
            }
            sb.append("| Column | Type | Nullable | Tags | Description |").append(nl());
            sb.append("| --- | --- | --- | --- | --- |").append(nl());
            for (FieldSpec field : schema.fields()) {
                sb.append("| `").append(field.name()).append("` | `").append(field.type()).append("` | ")
                  .append(field.nullable() ? "yes" : "no").append(" | ")
                  .append(field.tags().isEmpty() ? "-" : "`" + String.join("`, `", field.tags()) + "`")
                  .append(" | ").append(text(field.description())).append(" |").append(nl());
            }
            sb.append(nl());
        }
    }

    // -------------------------------------------------------------- reference

    private void reference(StringBuilder sb) {
        sb.append("## Transform reference").append(nl()).append(nl());
        sb.append("| `type:` | Configuration keys | What it does |").append(nl());
        sb.append("| --- | --- | --- |").append(nl());
        for (Transform transform : transforms.all()) {
            sb.append("| `").append(transform.type()).append("` | `")
              .append(String.join("`, `", new java.util.TreeSet<>(transform.configKeys())))
              .append("` | ").append(transform.summary()).append(" |").append(nl());
        }
        sb.append(nl());

        sb.append("## Quality rule reference").append(nl()).append(nl());
        sb.append("| `rule:` | Configuration keys | Can quarantine | What it checks |").append(nl());
        sb.append("| --- | --- | --- | --- |").append(nl());
        for (ExpectationRule rule : rules.all()) {
            sb.append("| `").append(rule.name()).append("` | `")
              .append(String.join("`, `", new java.util.TreeSet<>(rule.configKeys())))
              .append("` | ").append(rule instanceof dev.foundry.core.expect.RowRule ? "yes" : "no")
              .append(" | ").append(rule.summary()).append(" |").append(nl());
        }
        sb.append(nl());
    }

    // ---------------------------------------------------------------- helpers

    private static String text(String value) {
        if (value == null) {
            return "-";
        }
        return value.trim().replace("\n", " ").replace("|", "\\|");
    }

    private static String anchor(String name) {
        return name.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+", "-");
    }

    private static String nl() {
        return "\n";
    }
}
