package dev.foundry.core.docs;

import dev.foundry.core.Examples;
import dev.foundry.core.plan.PipelinePlan;
import dev.foundry.core.plan.Planner;
import dev.foundry.metadata.MetadataRepository;
import dev.foundry.metadata.model.PipelineSpec;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The catalogue is generated from the same documents the engine runs from, so
 * these tests check that what the metadata says reaches the page - including the
 * things a hand-maintained document always loses first: lineage, and the exact
 * type of every column.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class CatalogGeneratorTest {

    private static String catalogue;

    @BeforeAll
    void generate() {
        MetadataRepository repository = MetadataRepository.load(Examples.metadata());
        // The example includes a pipeline that names a custom transform, so the
        // planner needs to be able to see the plugin's classes.
        Planner planner = Planner.standard(Examples.pluginLoader());

        List<PipelinePlan> plans = new ArrayList<>();
        for (PipelineSpec pipeline : repository.pipelines()) {
            plans.add(planner.plan(repository, pipeline));
        }
        catalogue = new CatalogGenerator(repository, plans, planner.transforms(), planner.rules())
                .generate();
    }

    @Test
    @DisplayName("the page records which metadata it was generated from")
    void statesItsProvenance() {
        assertTrue(catalogue.contains("Generated by `foundry docs`"));
        assertTrue(catalogue.contains("Metadata fingerprint: `sha256:"));
        assertTrue(catalogue.contains("Do not edit by hand"));
    }

    @Test
    @DisplayName("every pipeline gets a section and a diagram")
    void documentsEveryPipeline() {
        assertTrue(catalogue.contains("### Pipeline: orders_daily"));
        assertTrue(catalogue.contains("### Pipeline: customer_profile"));
        assertTrue(catalogue.contains("```mermaid"));
        assertTrue(catalogue.contains("flowchart LR"));
    }

    @Test
    @DisplayName("parameters, steps and quality rules all reach the page")
    void documentsPipelineDetail() {
        assertTrue(catalogue.contains("#### Parameters"));
        assertTrue(catalogue.contains("`run_date`"));
        assertTrue(catalogue.contains("#### Steps"));
        assertTrue(catalogue.contains("`deduplicate`"));
        assertTrue(catalogue.contains("#### Quality rules"));
        assertTrue(catalogue.contains("`customer_is_known`"));
        assertTrue(catalogue.contains("quarantine"));
    }

    @Test
    @DisplayName("column lineage is published, traced back to the sources")
    void documentsLineage() {
        assertTrue(catalogue.contains("#### Column lineage"));
        assertTrue(catalogue.contains("`orders.quantity`"),
                "revenue should trace back to the quantity column of the landing file");
        assertTrue(catalogue.contains("`customers.region`"));
    }

    @Test
    @DisplayName("schemas are published with their types, tags and descriptions")
    void documentsSchemas() {
        assertTrue(catalogue.contains("### Schema: retail.orders.curated"));
        assertTrue(catalogue.contains("`decimal(14,2)`"));
        assertTrue(catalogue.contains("`pii:email`"), "data-protection tags survive into the catalogue");
        assertTrue(catalogue.contains("Net value of the line.")
                || catalogue.contains("quantity times price"));
    }

    @Test
    @DisplayName("datasets are published with their locations and enforcement")
    void documentsDatasets() {
        assertTrue(catalogue.contains("| `landing_orders` |"));
        assertTrue(catalogue.contains("${data}/landing/orders"));
        assertTrue(catalogue.contains("additive"));
        assertTrue(catalogue.contains("strict"));
    }

    @Test
    @DisplayName("a custom Java step is documented like any other")
    void documentsCustomSteps() {
        assertTrue(catalogue.contains("### Pipeline: order_risk"));
        assertTrue(catalogue.contains("| `scored` | `java` |"));
        assertTrue(catalogue.contains("`com.example.retail.OrderRiskScore`"),
                "the catalogue names the class, so a reader need not open the pipeline file");
        assertTrue(catalogue.contains("`array<string>`"),
                "a complex declared type reaches the page");
        assertTrue(catalogue.contains("`lines.line_total`"),
                "the lineage the step declared reaches the page, since nothing could infer it");
    }

    @Test
    @DisplayName("the reference sections list every transform and rule that exists")
    void documentsTheReference() {
        for (String type : Planner.standard().transforms().types()) {
            assertTrue(catalogue.contains("| `" + type + "` |"), "missing transform: " + type);
        }
        for (String rule : Planner.standard().rules().names()) {
            assertTrue(catalogue.contains("| `" + rule + "` |"), "missing rule: " + rule);
        }
    }

    @Test
    @DisplayName("generating twice gives byte-identical output")
    void isReproducible() {
        // A derived document that differs from itself between runs cannot be
        // committed and diffed, which is most of the reason for generating it.
        // Listings therefore keep the metadata's file order rather than a hash
        // map's, which the JVM randomises per process.
        MetadataRepository repository = MetadataRepository.load(Examples.metadata());
        Planner planner = Planner.standard(Examples.pluginLoader());

        String first = generate(repository, planner);
        String second = generate(repository, planner);
        assertEquals(first, second);

        // And again from a freshly loaded repository, which is what a build does.
        MetadataRepository reloaded = MetadataRepository.load(Examples.metadata());
        assertEquals(first, generate(reloaded, Planner.standard(Examples.pluginLoader())));
    }

    private static String generate(MetadataRepository repository, Planner planner) {
        List<PipelinePlan> plans = new ArrayList<>();
        for (PipelineSpec pipeline : repository.pipelines()) {
            plans.add(planner.plan(repository, pipeline));
        }
        return new CatalogGenerator(repository, plans, planner.transforms(), planner.rules())
                .generate();
    }

    @Test
    @DisplayName("the pipelines are listed in the order their files were read")
    void listsPipelinesInFileOrder() {
        // examples/retail/metadata/pipelines: customer_profile, order_risk, orders_daily
        int profile = catalogue.indexOf("### Pipeline: customer_profile");
        int risk = catalogue.indexOf("### Pipeline: order_risk");
        int daily = catalogue.indexOf("### Pipeline: orders_daily");
        assertTrue(profile < risk && risk < daily,
                "sections should follow path order, which is what makes the page stable");
    }

    @Test
    @DisplayName("a description containing a pipe does not break the table it sits in")
    void escapesTableCells() {
        assertTrue(catalogue.lines().filter(line -> line.startsWith("| `"))
                .allMatch(line -> line.endsWith("|")), "every table row is well formed");
    }
}
