#!/usr/bin/env python3
"""Builds every generated asset in the ROM.

    python3 tools/forge.py [--preview]

Writes src/gen/art.h and src/gen/art.c (font, sprites, palettes)
and assets/icon.bmp (the ROM's banner icon).
With --preview it also drops contact sheets into docs/art/ so the art can be
looked at without a DS.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(HERE, 'art'))

import font5x7            # noqa: E402
import png                # noqa: E402
import sprites            # noqa: E402
from palettes import UI, rgb555   # noqa: E402

GEN = os.path.join(ROOT, 'src', 'gen')

BANNER = ("/* Generated by tools/forge.py — do not edit by hand. */\n")


def c_bytes(data, per_line=16, indent='    '):
    out = []
    for i in range(0, len(data), per_line):
        out.append(indent + ', '.join(str(b) for b in data[i:i + per_line]) + ',')
    return '\n'.join(out)


def c_words(data, per_line=8, indent='    '):
    out = []
    for i in range(0, len(data), per_line):
        out.append(indent + ', '.join('0x%04X' % w for w in data[i:i + per_line]) + ',')
    return '\n'.join(out)


# ------------------------------------------------------------------ font ----

def emit_font(hdr, src):
    glyphs = font5x7.parse()
    first, last = font5x7.FIRST_CHAR, font5x7.LAST_CHAR
    rows = []
    for code in range(first, last + 1):
        rows.extend(glyphs[code])
    hdr.append("#define FONT_FIRST %d" % first)
    hdr.append("#define FONT_LAST  %d" % last)
    hdr.append("extern const uint8_t font5x7[%d][7];" % (last - first + 1))
    src.append("const uint8_t font5x7[%d][7] = {" % (last - first + 1))
    for i in range(0, len(rows), 7):
        src.append("    { " + ", ".join("0x%02X" % b for b in rows[i:i + 7]) + " },")
    src.append("};\n")
    return last - first + 1


# --------------------------------------------------------------- sprites ----

def emit_sprites(hdr, src):
    names = []
    for name, fn in sprites.ROSTER:
        canvas, pal = fn()
        names.append((name, canvas, pal))
        src.append("static const uint16_t pal_%s[%d] = {" % (name, len(pal)))
        src.append(c_words(pal))
        src.append("};")
        src.append("static const uint8_t pix_%s[%d] = {" % (name, canvas.w * canvas.h))
        src.append(c_bytes(canvas.px, 24))
        src.append("};")
        src.append("const Sprite spr_%s = { %d, %d, %d, 0, pal_%s, pix_%s };\n"
                   % (name, canvas.w, canvas.h, len(pal), name, name))
    hdr.append("")
    hdr.append("/* Sprites. SPR_* indexes the table; the named externs are for code")
    hdr.append("   that always draws the same thing (portraits, props). */")
    hdr.append("enum {")
    for i, (name, _, _) in enumerate(names):
        hdr.append("    SPR_%s = %d," % (name.upper(), i))
    hdr.append("    SPR_COUNT = %d" % len(names))
    hdr.append("};")
    for name, _, _ in names:
        hdr.append("extern const Sprite spr_%s;" % name)
    hdr.append("extern const Sprite *const sprite_table[SPR_COUNT];")
    src.append("const Sprite *const sprite_table[SPR_COUNT] = {")
    for name, _, _ in names:
        src.append("    &spr_%s," % name)
    src.append("};\n")
    return names




# ------------------------------------------------------------------ icon ----

def emit_icon():
    """A 32x32 banner icon: Carl's silhouette under the System's amber."""
    c = png.Canvas(32, 32)
    pal = [(0, 0, 0)]

    def ink(rgb):
        if tuple(rgb) not in pal:
            pal.append(tuple(rgb))
        return pal.index(tuple(rgb))

    bg = ink((16, 14, 24))
    glow = ink((58, 40, 20))
    amber = ink(UI['amber'])
    skin = ink((206, 158, 120))
    skin_d = ink((150, 110, 84))
    short = ink((66, 96, 176))
    hair = ink((62, 46, 38))
    dark = ink((10, 10, 14))

    c.rect(0, 0, 31, 31, bg)
    c.ellipse(16, 20, 15, 13, glow)
    # doorway of light behind him
    c.rect(11, 4, 21, 26, glow)
    c.rect(13, 6, 19, 26, ink((92, 62, 26)))
    # the crawler himself
    c.ellipse(16, 13, 4, 4, skin)
    c.ellipse(16, 10, 5, 3, hair)
    c.rect(12, 17, 20, 24, skin)
    c.rect(12, 17, 13, 24, skin_d)
    c.rect(11, 17, 12, 23, skin)
    c.rect(20, 17, 21, 23, skin)
    c.rect(12, 24, 20, 27, short)
    c.rect(13, 28, 15, 30, skin)
    c.rect(17, 28, 19, 30, skin)
    c.put(14, 12, dark)
    c.put(18, 12, dark)
    # amber system chrome
    c.rect(0, 0, 31, 1, amber)
    c.rect(0, 30, 31, 31, amber)
    c.put(2, 3, amber); c.put(29, 3, amber)
    c.put(2, 28, amber); c.put(29, 28, amber)

    while len(pal) < 16:
        pal.append((0, 0, 0))

    # A 4bpp Windows BMP, which is what ndstool wants for a banner.
    row_bytes = 16
    pixels = bytearray()
    for y in range(31, -1, -1):
        row = bytearray()
        for x in range(0, 32, 2):
            row.append((c.get(x, y) << 4) | c.get(x + 1, y))
        pixels += row
    palette = bytearray()
    for (r, g, b) in pal[:16]:
        palette += bytes((b, g, r, 0))
    header_size = 14 + 40 + len(palette)
    size = header_size + len(pixels)
    bmp = bytearray()
    bmp += b'BM'
    bmp += size.to_bytes(4, 'little') + b'\0\0\0\0' + header_size.to_bytes(4, 'little')
    bmp += (40).to_bytes(4, 'little') + (32).to_bytes(4, 'little') + (32).to_bytes(4, 'little')
    bmp += (1).to_bytes(2, 'little') + (4).to_bytes(2, 'little') + (0).to_bytes(4, 'little')
    bmp += len(pixels).to_bytes(4, 'little') + (2835).to_bytes(4, 'little') * 2
    bmp += (16).to_bytes(4, 'little') + (16).to_bytes(4, 'little')
    bmp += palette + pixels
    out = os.path.join(ROOT, 'assets', 'icon.bmp')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, 'wb').write(bytes(bmp))
    return out, c, pal


# --------------------------------------------------------------- previews ---

def preview_sheets(sprite_list, font_glyph_count, icon_canvas, icon_pal):
    out_dir = os.path.join(ROOT, 'docs', 'art')
    os.makedirs(out_dir, exist_ok=True)

    #  The walk cycles get their own sheet. A hundred and twenty sixteen-pixel
    #  frames dropped into hundred-pixel cells is two and a half thousand
    #  pixels of empty checkerboard, and the one thing worth looking at in
    #  them -- whether the frames actually differ -- is the thing that layout
    #  hides. On their own sheet they sit in rows, one row per facing, which
    #  is how a flipbook is read.
    walk = [e for e in sprite_list if e[0].startswith('ow_')]
    sprite_list = [e for e in sprite_list if not e[0].startswith('ow_')]

    cols, cell = 6, 100
    rows = (len(sprite_list) + cols - 1) // cols
    W, H = cols * cell, rows * cell
    buf = bytearray()
    for i in range(W * H):
        x, y = i % W, i // W
        v = 34 if ((x // 8 + y // 8) % 2) else 26
        buf += bytes((v, v, v + 6))

    def blit(canvas, pal, ox, oy):
        for y in range(canvas.h):
            for x in range(canvas.w):
                idx = canvas.get(x, y)
                if not idx:
                    continue
                v = pal[idx]
                r, g, b = (v & 31) << 3, ((v >> 5) & 31) << 3, ((v >> 10) & 31) << 3
                px, py = ox + x, oy + y
                if 0 <= px < W and 0 <= py < H:
                    o = (py * W + px) * 3
                    buf[o:o + 3] = bytes((r, g, b))

    for i, (name, canvas, pal) in enumerate(sprite_list):
        blit(canvas, pal, (i % cols) * cell + (cell - canvas.w) // 2,
             (i // cols) * cell + (cell - canvas.h) // 2)
    png.write_rgb(os.path.join(out_dir, 'cast.png'), W, H, buf)

    if walk:
        per_row = 10                      # six of a stride, then four of a breath
        zoom, pad = 3, 4
        cw = walk[0][1].w * zoom + pad
        chh = walk[0][1].h * zoom + pad
        rows = (len(walk) + per_row - 1) // per_row
        W2, H2 = per_row * cw + pad, rows * chh + pad
        buf2 = bytearray()
        for i in range(W2 * H2):
            x, y = i % W2, i // W2
            v = 34 if ((x // 8 + y // 8) % 2) else 26
            buf2 += bytes((v, v, v + 6))
        for i, (name, canvas, pal) in enumerate(walk):
            ox = pad + (i % per_row) * cw
            oy = pad + (i // per_row) * chh
            for y in range(canvas.h):
                for x in range(canvas.w):
                    idx = canvas.get(x, y)
                    if not idx:
                        continue
                    v = pal[idx]
                    r, g, b = (v & 31) << 3, ((v >> 5) & 31) << 3, ((v >> 10) & 31) << 3
                    for dy in range(zoom):
                        for dx in range(zoom):
                            px, py = ox + x * zoom + dx, oy + y * zoom + dy
                            if 0 <= px < W2 and 0 <= py < H2:
                                o = (py * W2 + px) * 3
                                buf2[o:o + 3] = bytes((r, g, b))
        png.write_rgb(os.path.join(out_dir, 'walk.png'), W2, H2, buf2)

    glyphs = font5x7.parse()
    scale, pad, cols = 3, 2, 16
    cw, ch = (5 + pad) * scale, (7 + pad) * scale
    rows = (font_glyph_count + cols - 1) // cols
    W, H = cols * cw, rows * ch
    buf = bytearray([18, 18, 26] * (W * H))
    for i in range(font_glyph_count):
        code = font5x7.FIRST_CHAR + i
        cx, cy = (i % cols) * cw, (i // cols) * ch
        for y in range(7):
            bits = glyphs[code][y]
            for x in range(5):
                if bits & (1 << (4 - x)):
                    for sy in range(scale):
                        for sx in range(scale):
                            o = ((cy + y * scale + sy) * W + cx + x * scale + sx) * 3
                            buf[o:o + 3] = bytes(UI['amber'])
    png.write_rgb(os.path.join(out_dir, 'font.png'), W, H, buf)
    print("  previews in docs/art/")


def main():
    os.makedirs(GEN, exist_ok=True)
    hdr = [BANNER, "#ifndef CRAWLER_GEN_ART_H", "#define CRAWLER_GEN_ART_H", "",
           "#include <stdint.h>", "", '#include "gfx.h"', ""]
    src = [BANNER, '#include "art.h"', ""]

    glyph_count = emit_font(hdr, src)
    sprite_list = emit_sprites(hdr, src)
    hdr.append("")
    hdr.append("#endif")

    open(os.path.join(GEN, 'art.h'), 'w').write("\n".join(hdr) + "\n")
    open(os.path.join(GEN, 'art.c'), 'w').write("\n".join(src) + "\n")

    icon_path, icon_canvas, icon_pal = emit_icon()

    print("forge:")
    print("  %d glyphs, %d sprites" % (glyph_count, len(sprite_list)))
    print("  %s" % os.path.relpath(icon_path, ROOT))
    total = sum(c.w * c.h for _, c, _ in sprite_list)
    print("  sprite pixels: %d bytes" % total)
    if '--preview' in sys.argv:
        preview_sheets(sprite_list, glyph_count, icon_canvas, icon_pal)


if __name__ == '__main__':
    main()
