#!/usr/bin/env python3
"""
Builds the web version of «اللمبي: مغامرات الحارة»:

1. Regenerates web/src/assets.js — the shared sprites (base64 PNG) and level
   texts, straight from Sources/ElLembyCore/Resources/.
2. Bundles all web/src modules into ONE self-contained HTML file with no
   external requests: web/ellemby.html (committed; open it from disk or host
   it anywhere). With --artifact PATH it also emits a body-only variant for
   publishing surfaces that supply their own <html>/<head> skeleton.

Run from the project root:  python3 tools/build_web.py
"""

import argparse
import base64
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "Sources", "ElLembyCore", "Resources")
WEB = os.path.join(ROOT, "web")
SRC = os.path.join(WEB, "src")

# Bundle order matters: dependencies first.
MODULES = [
    "config.js",
    "parser.js",
    "world.js",
    "bot.js",
    "audio.js",
    "assets.js",
    "render.js",
    "scenes.js",
    "input.js",
    "main.js",
]

SPRITE_NAMES = [
    "lemby_idle_0", "lemby_idle_1", "lemby_run_0", "lemby_run_1", "lemby_run_2",
    "lemby_jump_0", "lemby_hurt_0",
    "thug_walk_0", "thug_walk_1", "thug_squashed",
    "nousa_0", "nousa_1",
    "checkpoint_idle", "checkpoint_active",
    "coin_0", "coin_1", "coin_2", "coin_3",
    "sandwich", "heart",
    "tile_ground", "tile_dirt", "tile_brick", "tile_crate",
    "tile_mystery", "tile_crate_used", "tile_stone",
    "bg_far", "bg_near",
]

CSS = """
/* The page is the arcade cabinet: one deliberate dark world drawn from the
   game's own palette (its night tone), so single-theme is a choice here. */
:root { color-scheme: dark; }
html, body { margin: 0; padding: 0; background: #1e1a24; }
#ellemby {
  min-height: 100vh; display: flex; flex-direction: column;
  align-items: center; justify-content: center; gap: 12px;
  font-family: "Segoe UI", "Geeza Pro", "Noto Sans Arabic", sans-serif;
  touch-action: manipulation;
}
#game {
  image-rendering: pixelated; image-rendering: crisp-edges;
  background: #a6ccd8; border-radius: 4px;
  border: 1px solid rgba(243, 236, 224, 0.12);
  box-shadow: 0 16px 56px rgba(0, 0, 0, 0.55);
  max-width: 98vw;
}
#hint {
  color: #a99f8d; font-size: 13px; line-height: 1.7;
  direction: rtl; text-align: center; padding: 0 16px; max-width: 620px;
}
#touchpad { position: fixed; inset: auto 0 12px 0; display: flex; padding: 0 18px; pointer-events: none; }
.tbtn {
  pointer-events: auto; user-select: none; -webkit-user-select: none;
  width: 64px; height: 64px; border-radius: 50%;
  border: 2px solid rgba(243, 236, 224, 0.4);
  background: rgba(243, 236, 224, 0.12); color: #f3ece0;
  font-size: 22px; font-weight: bold; touch-action: none;
}
.tbtn:active { background: rgba(243, 236, 224, 0.3); }
.tbtn.right1 { order: 1; }
.tbtn.right2 { order: 2; margin-inline-start: 10px; }
.tbtn.left1 { order: 3; margin-inline-start: auto; width: 76px; height: 76px; }
"""

BODY = """
<div id="ellemby">
  <div id="hint">اللمبي: مغامرات الحارة — الأسهم أو A/D للحركة، المسافة للنط،
  P وقفة، M صوت. استنى ٧ ثواني على شاشة البداية تشوف العرض التجريبي! 🐪</div>
</div>
"""


def build_assets_js():
    parts = [
        "// GENERATED by tools/build_web.py — do not edit by hand.",
        "// The same pixel art and stages the macOS and Windows builds use.",
        "",
        "export const SPRITE_DATA = {",
    ]
    for name in SPRITE_NAMES:
        with open(os.path.join(RES, "sprites", name + ".png"), "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        parts.append(f'  {name}: "{b64}",')
    parts.append("};")
    parts.append("")
    parts.append("export const LEVELS = {")
    levels_dir = os.path.join(RES, "levels")
    for fname in sorted(os.listdir(levels_dir)):
        if fname.endswith(".txt"):
            with open(os.path.join(levels_dir, fname), encoding="utf-8") as f:
                text = f.read()
            key = fname[:-4]
            parts.append(f"  {key}: {text!r},".replace("\\n", "\\n"))
    parts.append("};")
    parts.append("")
    out = "\n".join(parts)
    with open(os.path.join(SRC, "assets.js"), "w", encoding="utf-8") as f:
        f.write(out)
    return out


def strip_module_syntax(source):
    lines = []
    for line in source.split("\n"):
        if re.match(r"^import\s.*from\s", line) or re.match(r"^import\s+[\"']", line):
            continue
        line = re.sub(r"^export\s+default\s+", "", line)
        line = re.sub(r"^export\s+", "", line)
        lines.append(line)
    return "\n".join(lines)


def bundle_js():
    chunks = []
    for name in MODULES:
        with open(os.path.join(SRC, name), encoding="utf-8") as f:
            chunks.append(f"// ===== {name} =====\n" + strip_module_syntax(f.read()))
    return '"use strict";\n(() => {\n' + "\n".join(chunks) + "\n})();"


def page(body_only):
    js = bundle_js()
    inner = f"<style>{CSS}</style>\n{BODY}\n<script>\n{js}\n</script>"
    if body_only:
        return inner
    return (
        "<!doctype html>\n<html lang=\"ar\" dir=\"rtl\">\n<head>\n"
        "<meta charset=\"utf-8\">\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\n"
        "<title>اللمبي: مغامرات الحارة</title>\n"
        "</head>\n<body>\n" + inner + "\n</body>\n</html>\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--artifact", help="also write a body-only variant to this path")
    args = ap.parse_args()

    build_assets_js()
    out_path = os.path.join(WEB, "ellemby.html")
    html = page(body_only=False)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"wrote web/ellemby.html ({len(html) / 1024:.0f} KB, fully self-contained)")

    if args.artifact:
        with open(args.artifact, "w", encoding="utf-8") as f:
            f.write(page(body_only=True))
        print(f"wrote artifact variant to {args.artifact}")


if __name__ == "__main__":
    main()
