#!/usr/bin/env python3
"""
Builds المرحلة ٢ «شارع السوق» (stage 2: Market Street) and writes it to
Sources/ElLembyCore/Resources/levels/level2.txt.

Harder than the alley: seven pits, market-stall crate walls to hop, a
double-decker risk/reward route, an optional high climb with a فول crate,
and — new mechanic — a عربية فول checkpoint (C) at the midpoint.

Legend (must match LevelParser.swift / LevelParser.cs):
    .  air          G  ground        D  dirt fill     B  brick
    X  crate        =  sandstone     ?  crate → coin  F  crate → sandwich
    o  coin         P  player        E  thug          N  Nousa (goal)
    C  checkpoint (عربية الفول)

Run from the project root:  python3 tools/build_level2.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Sources", "ElLembyCore", "Resources", "levels", "level2.txt")

COLS = 230
ROWS = 17
GROUND_ROW = 15

grid = [["." for _ in range(COLS)] for _ in range(ROWS)]


def put(row, col, ch):
    assert 0 <= row < ROWS and 0 <= col < COLS, (row, col)
    grid[row][col] = ch


def span(row, col0, col1, ch):
    for c in range(col0, col1 + 1):
        put(row, c, ch)


def column(col, row_top, row_bottom, ch):
    for r in range(row_top, row_bottom + 1):
        put(r, col, ch)


# --- ground, then carve the pits -------------------------------------------
span(GROUND_ROW, 0, COLS - 1, "G")
span(GROUND_ROW + 1, 0, COLS - 1, "D")

PITS = [(22, 24), (50, 53), (72, 74), (94, 96), (117, 120), (142, 144), (150, 152)]
for c0, c1 in PITS:
    span(GROUND_ROW, c0, c1, ".")
    span(GROUND_ROW + 1, c0, c1, ".")

# --- act 1: the stalls (cols 0–53) ------------------------------------------
put(14, 3, "P")

# crate stall steps with coins on top
put(14, 14, "X")
put(13, 14, "o")
column(17, 13, 14, "X")
column(18, 13, 14, "X")
span(12, 17, 18, "o")

# pit 1 (22–24), then the brick canopy over a thug pair
span(11, 27, 39, "B")
put(11, 30, "?")
put(11, 36, "F")
put(14, 29, "E")
put(14, 35, "E")
for c in (28, 32, 34, 38):
    put(13, c, "o")

# sandstone stairs up to a floating brick ledge (one hop above the stair
# top — an optional coin detour that stays out of the ground route)
put(14, 42, "=")
column(43, 13, 14, "=")
column(44, 12, 14, "=")
span(9, 45, 47, "B")
span(8, 45, 47, "o")

# raised takeoff stones before the wide pit 2 (50–53)
span(14, 48, 49, "=")

# --- act 2: the double-decker and the alley of walls (cols 54–112) ----------
# upper coin route on bricks; thug traffic below
span(10, 57, 61, "B")
span(10, 64, 68, "B")
span(9, 57, 60, "o")
span(9, 65, 68, "o")
for c in (58, 62, 66):
    put(14, c, "E")

# pit 3 (72–74)

# market stall walls to hop, coins between, a caged thug patrol
for c in (78, 84, 90):
    column(c, 13, 14, "X")
span(11, 80, 82, "o")
span(11, 86, 88, "o")
put(14, 86, "E")

# pit 4 (94–96) with a coin arc
span(10, 94, 96, "o")

# optional high route: stone outposts with a فول crate payoff
span(12, 100, 102, "=")
span(9, 105, 107, "=")
span(12, 110, 112, "=")
span(8, 105, 107, "o")
put(6, 106, "F")
span(11, 100, 102, "o")
span(11, 110, 112, "o")

# --- act 3: checkpoint, gauntlet, and the run home (cols 113–229) ------------
put(14, 113, "C")                      # عربية الفول — نقطة التفتيش
column(115, 13, 14, "=")               # takeoff blocks for pit 5 (117–120)
column(116, 13, 14, "=")

# the thug gauntlet under a brick canopy
span(11, 126, 136, "B")
put(11, 128, "?")
put(11, 134, "?")
for c in (125, 129, 133, 137):
    put(14, c, "E")
for c in (127, 131, 135):
    put(13, c, "o")

# rhythm pits 6 and 7 (142–144, 150–152) around a coin island
span(11, 145, 149, "o")

# double staircase with a coin crown
column(155, 14, 14, "=")
column(156, 13, 14, "=")
column(157, 12, 14, "=")
column(158, 11, 14, "=")
span(11, 159, 160, "=")
column(159, 12, 14, "=")
column(160, 12, 14, "=")
span(10, 158, 161, "o")
column(161, 12, 14, "=")
column(162, 13, 14, "=")
column(163, 14, 14, "=")

# home stretch
put(14, 172, "E")
put(14, 176, "E")
span(11, 174, 177, "o")
column(180, 13, 14, "X")
span(11, 183, 185, "o")

# Nousa in front of her street's buildings
put(14, 195, "N")
for r in range(5, GROUND_ROW):
    span(r, 202, COLS - 1, "B")

HEADER = """\
// اللمبي: مغامرات الحارة — المرحلة ٢ «شارع السوق»
// Stage 2 "Market Street". Generated by tools/build_level2.py — hand-edits
// work too, but re-running the tool overwrites this file.
//
// .  air          G  ground        D  dirt fill     B  brick
// X  crate        =  sandstone     ?  crate → coin  F  crate → sandwich
// o  coin         P  player        E  thug          N  Nousa (goal)
// C  checkpoint (عربية الفول)
"""


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for row in grid:
            f.write("".join(row).rstrip(".") or ".")
            f.write("\n")
    flat = ["".join(row) for row in grid]
    coins = sum(r.count("o") for r in flat)
    thugs = sum(r.count("E") for r in flat)
    print(f"wrote {OUT}: {COLS}×{ROWS}, {coins} coins, {thugs} thugs, "
          f"{len(PITS)} pits, 1 checkpoint")


if __name__ == "__main__":
    main()
