#!/usr/bin/env python3
"""
Builds المرحلة ١ «العنبر» (stage 1: "The Cell Block") and writes it to
Sources/ElLembyCore/Resources/levels/level1.txt.

The stage is authored here as code (spans, pits, placements) so the pacing
is easy to re-tune; the emitted .txt stays the file the game actually loads
— hand-editing it also works.

Legend (must match LevelParser.swift):
    .  air          G  ground        D  dirt fill     B  brick
    X  crate        =  sandstone     ?  crate → coin  F  crate → sandwich
    o  coin         P  player        E  thug          N  Nousa (goal)

Run from the project root:  python3 tools/build_level1.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Sources", "ElLembyCore", "Resources", "levels", "level1.txt")

COLS = 205
ROWS = 17           # one screen tall: 17 × 16px = 272
GROUND_ROW = 15     # cobblestone surface row; row 16 is dirt fill

grid = [["." for _ in range(COLS)] for _ in range(ROWS)]


def put(row, col, ch):
    assert 0 <= row < ROWS and 0 <= col < COLS, (row, col)
    grid[row][col] = ch


def span(row, col0, col1, ch):
    for c in range(col0, col1 + 1):
        put(row, c, ch)


# --- ground everywhere, then carve the pits -------------------------------
span(GROUND_ROW, 0, COLS - 1, "G")
span(GROUND_ROW + 1, 0, COLS - 1, "D")

PITS = [(33, 35), (50, 52), (80, 83), (106, 108), (126, 129)]
for c0, c1 in PITS:
    span(GROUND_ROW, c0, c1, ".")
    span(GROUND_ROW + 1, c0, c1, ".")

# --- act 1: the opening (learn to run, jump, bump crates) ------------------
put(14, 3, "P")                      # El-Lemby starts by his front door
span(11, 16, 19, "o")                # first coin row: jump practice
put(14, 22, "E")                     # first thug on open ground
# classic first crate row: B ? B F B
put(11, 24, "B")
put(11, 25, "?")
put(11, 26, "B")
put(11, 27, "F")                     # the فول sandwich lives here
put(11, 28, "B")

# pit 1 (33–35), then a brick ledge with coins
span(12, 39, 42, "B")
span(11, 39, 42, "o")
put(14, 46, "E")

# pit 2 (50–52) with a coin arc over it
span(10, 50, 52, "o")

# --- act 2: the middle (stairs, gauntlet, overhead crates) -----------------
# small sandstone pyramid
put(14, 58, "=")
span(13, 59, 59, "=")
put(14, 59, "=")
for r in (12, 13, 14):
    put(r, 60, "=")
span(11, 59, 60, "o")

span(11, 66, 69, "o")
put(14, 66, "E")

# elevated bricks with a mystery crate; coins collected running underneath
span(10, 72, 75, "B")
put(10, 74, "?")
span(13, 72, 75, "o")

# raised takeoff stones before the wide pit 3 (80–83)
span(14, 78, 79, "=")

# the market gauntlet: three thugs + overhead crates
for c in (88, 94, 100):
    put(14, c, "E")
span(11, 90, 98, "B")
put(11, 92, "?")
put(11, 96, "F")
for c in (91, 93, 95, 97):
    put(13, c, "o")

# pit 4 (106–108), then a breather coin row
span(11, 110, 113, "o")

# --- act 3: the finale (grand staircase, leap, home stretch) ---------------
# ascending sandstone staircase, Mario-style
put(14, 120, "=")
for r in (13, 14):
    put(r, 121, "=")
for r in (12, 13, 14):
    put(r, 122, "=")
for r in (11, 12, 13, 14):
    put(r, 123, "=")
for r in (10, 11, 12, 13, 14):
    put(r, 124, "=")
span(9, 123, 124, "o")

# leap over pit 5 (126–129) from the staircase top, then step down
for r in (12, 13, 14):
    put(r, 131, "=")
for r in (13, 14):
    put(r, 132, "=")
put(14, 133, "=")
span(11, 131, 132, "o")

# cooldown stretch with the last thug pair
put(14, 140, "E")
put(14, 144, "E")
span(12, 147, 149, "o")

# a crate wall to hop and one last mystery crate
span(13, 154, 154, "X")
put(14, 154, "X")
put(11, 156, "?")

span(11, 164, 167, "o")
put(14, 170, "E")

# --- Nousa's house ----------------------------------------------------------
put(14, 190, "N")
for r in range(5, GROUND_ROW):
    span(r, 196, COLS - 1, "B")

HEADER = """\
// اللمبي: اللي بالي بالك — المرحلة ١ «العنبر»
// Stage 1 "The Cell Block". Generated by tools/build_level1.py — hand-edits work
// too, but re-running the tool overwrites this file.
//
// .  air          G  ground        D  dirt fill     B  brick
// X  crate        =  sandstone     ?  crate → coin  F  crate → sandwich
// o  coin         P  player        E  thug          N  Nousa (goal)
"""


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for row in grid:
            f.write("".join(row).rstrip(".") or ".")
            f.write("\n")
    coins = sum(r.count("o") for r in ("".join(row) for row in grid))
    thugs = sum(r.count("E") for r in ("".join(row) for row in grid))
    print(f"wrote {OUT}: {COLS}×{ROWS}, {coins} coins, {thugs} thugs, {len(PITS)} pits")


if __name__ == "__main__":
    main()
