// Skeletons and sampled animation clips (.qskel / .qanim), generated by tools/art.
// Every bone's bind frame is axis-aligned with the character (Z up, facing -Y), so clips are
// plain local rotations and retarget across characters that share bone names.
#pragma once
#include "core/math.hpp"
#include "core/pack.hpp"
#include <string>
#include <vector>

namespace q {

struct Bone {
    std::string name;
    int parent = -1;
    Xform bind;       // local, relative to parent
    mat4 inv_bind;    // model space -> bone space
};

struct Skeleton {
    std::vector<Bone> bones;
    bool load(Blob b);
    int find(const std::string& name) const;
};

struct AnimEvent {
    std::string name;
    float time;
};

struct Clip {
    std::string name;
    float fps = 30;
    int frames = 0;
    bool loop = false;
    int bone_count = 0;
    std::vector<Xform> samples;  // frames * bone_count (t, r)
    std::vector<AnimEvent> events;
    float duration() const { return frames > 1 ? (frames - 1) / fps : 0.f; }
    void sample(float t, std::vector<Xform>& out) const;
    float event_time(const char* name, float def = -1) const;
};

struct AnimSet {
    std::vector<Clip> clips;
    bool load(Blob b);
    const Clip* find(const std::string& name) const;
};

// Local pose -> model-space matrices -> skinning palette (3 rows of a 3x4 per bone).
struct Pose {
    std::vector<Xform> local;
    std::vector<mat4> model;
    void resize(size_t n) { local.resize(n); model.resize(n); }
    void set_bind(const Skeleton& s);
    void compute_model(const Skeleton& s, const mat4& root = mat4());
    void write_palette(const Skeleton& s, float* rows) const;  // 12 floats per bone
};

void blend_pose(std::vector<Xform>& a, const std::vector<Xform>& b, float w);

}  // namespace q
