import { CONFIG } from '../config';

/**
 * Liberated Pixel Cup character layers.
 *
 * LPC sheets are a fixed grid: 64×64 frames, one row per facing in the order
 * up, left, down, right, and one column per animation frame. Every layer — body,
 * legs, torso, head, helmet, weapon — shares that grid exactly, so a character
 * is built by stacking layers in z order and reading the same cell from each.
 *
 * That is why this is worth the trouble over drawing characters procedurally:
 * the walk is nine hand-drawn frames per facing with real weight in it, and the
 * gear is drawn to match the body pose frame for frame. Nothing generated at
 * this size competes with it.
 *
 * Attribution for every file lives in `public/lpc/CREDITS.md`, regenerated by
 * `tools/vendor-lpc.mjs`. OGA-BY and CC-BY-SA both require it to ship.
 */

/** side of one LPC cell, in pixels */
export const CELL = 64;

/** Row order inside every LPC sheet. */
export const DIR = { up: 0, left: 1, down: 2, right: 3 } as const;
export type DirName = keyof typeof DIR;

/**
 * Facings actually baked. `left` is omitted and drawn by flipping `right`:
 * LPC draws it as its own art, but at this size the only difference is which
 * hand the weapon is in, and halving the unit frames is what keeps the sheet
 * inside one texture.
 */
export const BAKED_DIRS: DirName[] = ['up', 'down', 'right'];

/** Frames per animation in the sheets we ship. */
export const LPC_WALK = 9;
export const LPC_THRUST = 8;
export const LPC_SHOOT = 13;

/**
 * Attack frames baked per unit. The thrust and shoot cycles are longer than
 * this, but they spend most of their length on the wind-up; sampling evenly
 * across the cycle keeps the recognisable poses and a third of the atlas cost.
 */
export const ATTACK_BAKED = 6;

export type Anim = 'walk' | 'thrust' | 'shoot';

/** One stacked layer of a character. Higher `z` paints later. */
export interface Layer {
  /** vendored sheet name, without the `_<anim>.png` suffix */
  sheet: string;
  z: number;
  /**
   * Recolour applied to this layer only, as a multiply. Era progression rides
   * on this: the same plate armour becomes iron, brass, steel, olive drab and
   * neon without five sets of art.
   */
  tint?: number;
  /** skip this layer when the animation is missing from the vendored set */
  optional?: boolean;
}

const IMAGES = new Map<string, HTMLImageElement>();

function loadImage(url: string): Promise<HTMLImageElement | null> {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = url;
  });
}

/**
 * Load every vendored sheet named by `sheets`, for every animation. Missing
 * combinations resolve to null and are simply skipped when compositing, so a
 * layer that has no `shoot` art costs a hole in that pose rather than a crash.
 */
export async function loadLpc(base: string, sheets: string[], anims: Anim[]): Promise<void> {
  // the one-file build has nowhere to fetch from and inlines the sheets instead
  const embedded = (window as unknown as { __CC_LPC__?: Record<string, string> }).__CC_LPC__;
  const jobs: Promise<void>[] = [];
  for (const s of sheets) {
    for (const a of anims) {
      const key = `${s}_${a}`;
      const src = embedded?.[`${key}.png`] ?? `${base}lpc/${key}.png`;
      jobs.push(loadImage(src).then((img) => {
        if (img) IMAGES.set(key, img);
      }));
    }
  }
  await Promise.all(jobs);
}

export const hasSheet = (sheet: string, anim: Anim): boolean => IMAGES.has(`${sheet}_${anim}`);

/** Scratch canvases: one to tint a single layer, one to stack the result. */
let tintCv: HTMLCanvasElement | null = null;
let tintCtx: CanvasRenderingContext2D | null = null;

function tinted(img: HTMLImageElement, sx: number, sy: number, tint: number): CanvasImageSource {
  if (!tintCv) {
    tintCv = document.createElement('canvas');
    tintCv.width = CELL;
    tintCv.height = CELL;
    tintCtx = tintCv.getContext('2d')!;
  }
  const c = tintCtx!;
  c.globalCompositeOperation = 'source-over';
  c.clearRect(0, 0, CELL, CELL);
  c.drawImage(img, sx, sy, CELL, CELL, 0, 0, CELL, CELL);
  // multiply keeps the art's own shading and pushes it toward the era colour;
  // source-atop then confines the result to the pixels the layer already drew,
  // so the transparent margin stays transparent
  c.globalCompositeOperation = 'multiply';
  c.fillStyle = '#' + (tint >>> 0).toString(16).padStart(6, '0');
  c.fillRect(0, 0, CELL, CELL);
  c.globalCompositeOperation = 'destination-in';
  c.drawImage(img, sx, sy, CELL, CELL, 0, 0, CELL, CELL);
  c.globalCompositeOperation = 'source-over';
  return tintCv;
}

/**
 * Draw one composited character cell into `dst` at (dx, dy).
 *
 * `frame` indexes the animation's own frame count, `dir` picks the row. Layers
 * are painted in ascending z; a layer with no art for this animation is
 * skipped, which is how a weapon that only has a walk sheet still works.
 */
export function drawCell(
  dst: CanvasRenderingContext2D,
  layers: Layer[],
  anim: Anim,
  dir: DirName,
  frame: number,
  dx: number,
  dy: number,
): void {
  const row = DIR[dir];
  for (const l of [...layers].sort((a, b) => a.z - b.z)) {
    const img = IMAGES.get(`${l.sheet}_${anim}`);
    if (!img) continue;
    const cols = Math.max(1, Math.floor(img.naturalWidth / CELL));
    const sx = (frame % cols) * CELL;
    const sy = row * CELL;
    if (sy + CELL > img.naturalHeight) continue;
    if (l.tint !== undefined) dst.drawImage(tinted(img, sx, sy, l.tint), dx, dy);
    else dst.drawImage(img, sx, sy, CELL, CELL, dx, dy, CELL, CELL);
  }
}

/** How many frames an animation's sheets actually have. */
export function frameCount(anim: Anim): number {
  return anim === 'walk' ? LPC_WALK : anim === 'thrust' ? LPC_THRUST : LPC_SHOOT;
}

/**
 * Evenly sample `ATTACK_BAKED` frames out of an attack cycle, always including
 * the first and last so the pose starts at rest and ends at full extension.
 */
export function attackFrameAt(anim: Anim, i: number): number {
  const n = frameCount(anim);
  return Math.round((i / (ATTACK_BAKED - 1)) * (n - 1));
}

// ---------------------------------------------------------------- characters

/**
 * The layer stack for a soldier or king, per era and tier.
 *
 * Tier picks the armour — leather levy, chainmail drilled, plate elite — and
 * the era recolours it, so fifteen distinct-looking soldiers come out of three
 * sets of art. z values follow LPC's own ordering: body under legs under torso
 * under head under helmet, with the weapon on top.
 */
export function unitLayers(era: number, tier: number, royal: boolean): Layer[] {
  const pal = CONFIG.palettes[era];
  const metal = ERA_METAL[era];
  // The king wears the same plate as an elite, pushed gold. LPC's armour is cut
  // for the standard body, not the muscular one — putting it on the muscular
  // base leaves the chest bare, so the king is distinguished by colour and
  // crest rather than by frame size.
  const royalGold = 0xe6c46a;
  const torso = royal ? 'torso_plate' : tier === 0 ? 'torso_leather' : tier === 1 ? 'torso_chain' : 'torso_plate';
  const legs = royal || tier === 2 ? 'legs_plate' : 'legs_pants';
  const feet = royal || tier === 2 ? 'feet_plate' : 'feet_boots';
  const helm = royal
    ? 'helm_armet'
    : tier === 0 ? 'hat_cloth' : tier === 1 ? 'helm_legion' : era >= 3 ? 'helm_xeon' : 'helm_bascinet';

  const armour = royal ? royalGold : metal;
  const layers: Layer[] = [
    { sheet: 'body_male', z: 10 },
    // cloth takes the era's accent, plate takes its metal — tinting trousers
    // with steel makes them look like foil
    { sheet: legs, z: 25, tint: legs === 'legs_plate' ? armour : undefined },
    { sheet: feet, z: 30, tint: feet === 'feet_plate' ? armour : undefined },
    { sheet: torso, z: 60, tint: torso === 'torso_leather' ? undefined : armour },
    { sheet: 'head_human', z: 100 },
    { sheet: helm, z: 130, tint: helm === 'hat_cloth' ? undefined : armour },
  ];
  // LPC covers the ends of the arc: a longsword for the iron age and a glowing
  // blade for neon. The powder, industry and steel eras have no firearms in the
  // set at all, so their weapons are drawn by the game — see weaponOverlay().
  if (era === 0) layers.push({ sheet: 'weapon_sword', z: 140 });
  else if (era === 4) layers.push({ sheet: 'weapon_glow', z: 140, tint: pal.accent });
  return layers;
}

/**
 * Era metal colours. Multiplied over LPC's own grey steel, so the shading and
 * highlights are the original artists' and only the hue moves.
 */
const ERA_METAL = [0xb9c0c8, 0xc9a06a, 0x8fa2b4, 0x8d9478, 0x9fd8e8];

/** Monster layer stacks for the horde. */
export function enemyLayers(kind: string): Layer[] {
  switch (kind) {
    case 'runner':
      return [{ sheet: 'body_skeleton', z: 10 }, { sheet: 'head_skeleton', z: 100 }];
    case 'brute':
      return [
        { sheet: 'body_king', z: 10 }, { sheet: 'head_minotaur', z: 100 },
        { sheet: 'legs_pants', z: 25 }, { sheet: 'feet_boots', z: 30 },
      ];   // the muscular base, bare-chested: a brute should not look kitted out
    case 'shooter':
      return [{ sheet: 'body_zombie', z: 10 }, { sheet: 'head_zombie', z: 100 }];
    case 'boss':
      return [
        { sheet: 'body_male', z: 10 }, { sheet: 'head_orc', z: 100 },
        { sheet: 'torso_plate', z: 60 }, { sheet: 'legs_plate', z: 25 },
        { sheet: 'feet_plate', z: 30 }, { sheet: 'weapon_sword', z: 140 },
      ];
    default:
      return [{ sheet: 'body_skeleton', z: 10 }, { sheet: 'head_goblin', z: 100 }];
  }
}

/** Every sheet name the game needs loaded. */
export const SHEETS = [
  'body_male', 'body_king', 'body_skeleton', 'body_zombie',
  'head_human', 'head_skeleton', 'head_orc', 'head_goblin', 'head_minotaur', 'head_zombie',
  'torso_leather', 'torso_chain', 'torso_plate', 'torso_legion',
  'legs_pants', 'legs_plate', 'feet_boots', 'feet_plate',
  'hat_cloth', 'helm_legion', 'helm_bascinet', 'helm_armet', 'helm_xeon',
  'weapon_sword', 'weapon_glow',
];
